### ISSUE TITLE
assets_icons.h 🤮 

### ISSUE THREAD

**Issue by RogueMaster** [QtRoS/flipper-zero-hex-viewer#3]
Remove [Line 8 of hex_viewer.h](https://github.com/QtRoS/flipper-zero-hex-viewer/blob/master/hex_viewer.h#L8C1-L8C26) as it is not needed and will allow you to get https://github.com/flipperdevices/flipper-application-catalog/pull/176 approved...

**Comment by QtRoS** [comment]
It's fixed by now
